#ifndef GLOBALS_H
#define GLOBALS_H

#define TELEMETRY_VERSION_MAJOR	"0"
#define TELEMETRY_VERSION_MINOR	"0"
#define TELEMETRY_VERSION_MICRO	"1"
#define TELEMETRY_VERSION \
	TELEMETRY_VERSION_MAJOR "." \
	TELEMETRY_VERSION_MINOR "." \
	TELEMETRY_VERSION_MICRO

#define TELEMETRY_BANNER	"Telemetry (" TELEMETRY_VERSION ")"

#define FTDI_VENDOR_ID		0x403
#define FTDI_PRODUCT_ID		0x6001
#define FTDI_DEFAULT_BAUDRATE	9600

#endif
